format = """
[╭──](blue)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
\n[╰──  ](blue)\
"""

add_newline = true

[username]
style_user = "blue"
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[ 󰁥 $hostname$ssh_symbol](blue)'
trim_at = '.'
disabled = false
ssh_symbol = '  '

[directory]
style = "purple"
format = "[  $path]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = " 󱍙 "
"Pictures" = "  "

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Windows = "  "
Macos = "  "
Ubuntu = " 󰕈 "
Arch = "  "
Android = "  "

[git_branch]
symbol = " 󰘬 "
format = '[[$symbol$branch](fg:#769ff0)]($style)'
style = "purple"
