[tools]
bat = "latest"
codex = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
helix = "latest"
just = "latest"
neovim = "latest"
opencode = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
television = "latest"
typst = "latest"
uv = "latest"
zoxide = "latest"
node = "22"
pi = "latest"
tmux = "latest"
